### ISSUE TITLE
No publishing options available under Proton

### ISSUE THREAD

**Issue by ptkato** [BUTR/Bannerlord.ButterLib#277]
![image](https://user-images.githubusercontent.com/10677806/211149218-206fcb56-e2c2-4edd-8b96-00bb2adfad28.png)

I'm playing under Proton and everything works dandy, except the publishing bits of butterlib, as can be seen in the screenshot, could I be missing some dependency?

**Comment by Aragas** [comment]
Sorry for the long answer! This happens when the Crash Uploader Subsystem is disabled in the ButterLib settings!

**Comment by Aragas** [comment]
Closing due to no response
