### ISSUE TITLE
Issue with Game Pass PC version

### ISSUE THREAD

**Issue by NoNick96** [BUTR/Bannerlord.ButterLib#296]
Currently the mod doesn't work for the Game Pass edition of the game. The game crashes on start up with this mod ButterLib Version v2.6.3 loaded. For the game pass version folder "Win64_Shipping_Client" has to be renamed to "Gaming.Desktop.x64_Shipping_Client". I've done that manually, but game still crashes on start up. Please update.

**Comment by ZombiePippin** [comment]
I have the same problem, I read somewhere that they are working on this and we'll just have to wait.

**Comment by Aragas** [comment]
Yep, we're working on the Game Pass PC Version!

**Comment by Aragas** [comment]
Done!
