### ISSUE TITLE
Missing Method Exception

### ISSUE THREAD

**Issue by billw2012** [BUTR/Bannerlord.ButterLib#40]
> System.MissingMethodException: Method not found: 'Boolean Bannerlord.ButterLib.SaveSystem.Extensions.IDataStoreExtensions.SyncDataAsJson(TaleWorlds.CampaignSystem.IDataStore, System.String, !!0 ByRef, Newtonsoft.Json.JsonSerializerSettings)'.

I can confirm at the point where the exception occurs that the expected version of Bannerlord.ButterLib.dll is loaded, from the expected location. I can even confirm that the type exists in the loaded assembly (at least according to the `Assembly` metadata).

Link from your own crash reporter (which is awesome): https://crash.butr.dev/report/29927686.html

**Comment by Aragas** [comment]
What an interesting exception!
What version of ButterLib is used as a dependency for `BLTAdoptAHero`?

**Comment by billw2012** [comment]
1.0.22.0. I have only one instance of the dll on my machine (confirmed with Search Everything), and confirmed that this path is where it is loaded from. 
```
<Reference Include="Bannerlord.ButterLib, Version=1.0.22.0, Culture=neutral, PublicKeyToken=null">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\Modules\Bannerlord.ButterLib\bin\Win64_Shipping_Client\Bannerlord.ButterLib.dll</HintPath>
      <Private>False</Private>
</Reference>
```

**Comment by Aragas** [comment]
While I'm not sure it's the case, is there any particular reason why you won't use the NuGet package?
```xml
    <PackageReference Include="Bannerlord.ButterLib" Version="1.0.22" IncludeAssets="compile" />
```

**Comment by billw2012** [comment]
Okay I found the problem: I was using another version of Newtonsoft.Json (required for other libraries I am using), if I switch back to using the game skipped version it works correctly now!

**Comment by Aragas** [comment]
Good to know! Never knew that the version difference can cause the public API to break
