### ISSUE TITLE
MBObjectManager.GetObject Type Not Registered loading 1.5.9 save in 1.6.0

### ISSUE THREAD

**Issue by billw2012** [BUTR/Bannerlord.ButterLib#43]
Using the new 1.6.0 release of BL.
Report here: https://crash.butr.dev/report/BF5F9D15.html

**Comment by billw2012** [comment]
In fact just starting a new sandbox game is also crashing, with only Harmony and Butterlib:
![image](https://user-images.githubusercontent.com/1453936/121758494-6c81d100-cb19-11eb-8fe2-c69fa794493a.png)

**Comment by billw2012** [comment]
Seems fixed now

**Comment by Aragas** [comment]
Thanks for the report, forgot to answer back that the issue has been resolved!
